import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import {Metadata} from "next";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "NoteNest",
  description: "Generated by create next app",
  icons : {
    icon : [
      '/favicon.ico?v=4',
    ],
    apple:[
      '/apple-touch-icon.png?v=4',
    ],
    shortcut: [
      '/apple-touch-icon.png'
    ]
  },
  manifest : '/site.webmanifest'
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </html>
  );
}